export type RedditPost = {
  kind: "t3";
  data: {
    approved_at_utc: null;
    subreddit: string;
    selftext: string;
    author_fullname: string;
    saved: boolean;
    mod_reason_title: string | null;
    gilded: number;
    clicked: boolean;
    title: string;
    link_flair_richtext: string[];
    subreddit_name_prefixed: string;
    hidden: boolean;
    pwls: null;
    link_flair_css_class: string | null;
    downs: number;
    thumbnail_height: number;
    top_awarded_type: string | null;
    hide_score: boolean;
    name: string;
    quarantine: boolean;
    link_flair_text_color: string;
    upvote_ratio: number;
    author_flair_background_color: string | null;
    subreddit_type: string;
    ups: number;
    total_awards_received: number;
    media_embed: {
      content: string;
      width: number;
      scrolling: boolean;
      height: number;
    };
    thumbnail_width: number;
    author_flair_template_id: string | null;
    is_original_content: boolean;
    user_reports: object;
    secure_media: object;
    is_reddit_media_domain: boolean;
    is_meta: boolean;
    category: null;
    secure_media_embed: object[];
    link_flair_text: null;
    can_mod_post: boolean;
    score: number;
    approved_by: null;
    is_created_from_ads_ui: boolean;
    author_premium: boolean;
    thumbnail: string;
    edited: boolean;
    author_flair_css_class: null;
    author_flair_richtext: [];
    gildings: object;
    post_hint: string;
    content_categories: null;
    is_self: boolean;
    mod_note: null;
    created: number;
    link_flair_type: string;
    wls: null;
    removed_by_category: null;
    banned_by: null;
    author_flair_type: string;
    domain: string;
    allow_live_comments: boolean;
    selftext_html: null;
    likes: null;
    suggested_sort: null;
    banned_at_utc: null;
    url_overridden_by_dest: string;
    view_count: null;
    archived: boolean;
    no_follow: boolean;
    is_crosspostable: boolean;
    pinned: boolean;
    over_18: boolean;
    preview: object;
    all_awardings: [];
    awarders: [];
    media_only: boolean;
    can_gild: boolean;
    spoiler: boolean;
    locked: boolean;
    author_flair_text: null;
    treatment_tags: [];
    visited: boolean;
    removed_by: null;
    num_reports: null;
    distinguished: null;
    subreddit_id: string;
    author_is_blocked: boolean;
    mod_reason_by: null;
    removal_reason: null;
    link_flair_background_color: string;
    id: string;
    is_robot_indexable: boolean;
    report_reasons: null;
    author: string;
    discussion_type: null;
    num_comments: number;
    send_replies: boolean;
    whitelist_status: null;
    contest_mode: boolean;
    mod_reports: [];
    author_patreon_flair: boolean;
    author_flair_text_color: null;
    permalink: string;
    parent_whitelist_status: null;
    stickied: boolean;
    url: string;
    subreddit_subscribers: number;
    created_utc: number;
    num_crossposts: number;
    media: {
      oembed: {
        provider_url: string;
        description: string;
        title: string;
        type: string;
        thumbnail_width: number;
        height: number;
        width: number;
        html: string;
        version: string;
        provider_name: string;
        thumbnail_url: string;
        thumbnail_height: number;
        author_url: string;
      };
    };
    is_video: boolean;
  };
};

export type RedditResponseData = {
  kind: string;
  data: {
    after: string;
    dist: number;
    modhash: string;
    geo_filter: string | null;
    children: RedditPost[];
  };
};

export type YouTubeVideo = {
  id: string;
  title: string;
  description: string;
  duration: string;
  thumbnail: string;
  publishedAt: string;
};

export type VideoData = {
  id: string;
  title: string;
  thumbnail: string;
  url: string;
  author: string;
};
